import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// English translations (default)
const en = {
  translation: {
    // Header
    features: "Features",
    howItWorks: "How it works",
    pricing: "Pricing",
    login: "Log in",
    startFreeTrial: "Start Free Trial",
    
    // Hero
    tagline: "AI life assistant for adults 25–50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "The assistant thinks ahead for you.",
    heroDescription: "Automate your tasks, money, and daily routines with a single AI assistant built for real life — not just work.",
    aiPlansDay: "AI plans your day",
    clearSpending: "Clear spending view",
    smarterRoutines: "Smarter routines",
    oneAppForLife: "One app for life",
    tryFreeForever: "Try Free Forever",
    noCreditCard: "No credit card needed for Free plan. Cancel or downgrade anytime.",
    
    // Daily Plan
    todayWithMindPilot: "Today with MindPilot",
    aiModeActive: "AI mode: Active",
    dailyPlanGenerated: "Daily plan generated by AI",
    planningYourDay: "Here's how I'm planning your day:",
    deepWorkBlock: "Deep work block",
    highFocusTasks: "9:00–11:00 · High-focus tasks",
    billsMoneyCheckIn: "Bills & money check-in",
    billDueIn3Days: "You have 1 bill due in 3 days",
    energyBreakStretch: "Energy break & stretch",
    basedOnCalendar: "3:00 PM · Based on your calendar",
    eveningRecap: "Evening recap",
    summaryAt9PM: "I'll send a 60-second summary at 9 PM",
    priority: "Priority",
    finance: "Finance",
    wellness: "Wellness",
    summary: "Summary",
    
    // Features
    featuresTitle: "Everything you need, powered by AI.",
    featuresDescription: "MindPilot AI combines tasks, finances, routines, coaching, and summaries into one intelligent assistant.",
    aiTaskPilot: "AI Task Pilot",
    aiTaskPilotDesc: "Auto-generated daily tasks, priority sorting, smart reminders",
    smartMoneyView: "Smart Money View",
    smartMoneyViewDesc: "Track spending, see patterns, get gentle budget alerts",
    lifeOrganizerHub: "Life Organizer Hub",
    lifeOrganizerHubDesc: "Keep documents and notes in one secure, searchable place",
    wellnessCoach: "Wellness Coach",
    wellnessCoachDesc: "Sleep, breaks, movement nudges at the right moments",
    goalNavigator: "Goal Navigator",
    goalNavigatorDesc: "Set monthly goals with realistic weekly action plans",
    smartSummaries: "Smart Summaries",
    smartSummariesDesc: "AI reads the long stuff, gives you the 10-second version",
    tasks: "Tasks",
    money: "Money",
    organization: "Organization",
    habits: "Habits",
    goals: "Goals",
    summaries: "Summaries",
    tryNow: "Try Now",
    
    // How it works
    howItWorksTitle: "From sign-up to \"life on autopilot\" in 3 steps.",
    howItWorksDescription: "Get started in minutes and let MindPilot take over the mental load.",
    step1Title: "Sign up & connect",
    step1Desc: "Create your account and tell MindPilot about your goals and habits.",
    step2Title: "AI learns your routine",
    step2Desc: "MindPilot analyzes your patterns and starts building your personalized system.",
    step3Title: "Life on autopilot",
    step3Desc: "Wake up to a planned day, tracked finances, and wellness reminders — all automatic.",
    aiPoweredAutomation: "AI-powered automation",
    learnsAndAdapts: "Learns and adapts to you",
    
    // Pricing
    pricingTitle: "Simple, transparent pricing",
    pricingDescription: "Start with a 7-day free trial or unlock everything with Premium.",
    freeForever: "Free Trial",
    premium: "Premium",
    lifetime: "7 days free",
    perMonth: "/month",
    mostPopular: "Most Popular",
    startFree: "Start Free",
    start7DayTrial: "Start 7-Day Free Trial",
    
    // Free features
    freeFeature1: "15 AI responses per day",
    freeFeature2: "Manual task management",
    freeFeature3: "Basic mood tracking",
    freeFeature4: "Up to 10 documents",
    freeFeature5: "3 goals per month",
    freeFeature6: "5 summaries per day",
    
    // Premium features
    premiumFeature1: "Unlimited AI responses",
    premiumFeature2: "Auto-generated daily tasks",
    premiumFeature3: "Smart financial sync & insights",
    premiumFeature4: "Unlimited cloud storage",
    premiumFeature5: "Unlimited goals + action plans",
    premiumFeature6: "Priority AI processing",
    premiumFeature7: "No ads, encrypted backup",
    
    // Footer
    privacy: "Privacy",
    terms: "Terms",
    support: "Support",
    allRightsReserved: "All rights reserved.",
    
    // Register/Login
    registerTitle: "Create New Account",
    loginTitle: "Log In",
    welcomeBack: "Welcome back! Please log in to your account",
    startTrialToday: "Start your 7-day free trial today",
    loginWithGoogle: "Log in with Google",
    registerWithGoogle: "Sign up with Google",
    or: "or",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    password: "Password",
    minChars: "Minimum 6 characters",
    agreeToTerms: "I agree to the",
    termsAndConditions: "Terms & Conditions",
    and: "and",
    privacyPolicy: "Privacy Policy",
    startTrialButton: "Start Free Trial",
    loginButton: "Log In",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    registerNow: "Register now",
    backToHome: "← Back to home",
    
    // Register features
    whatYouGet: "What you get",
    feature7DayTrial: "7-day free trial",
    featureAIAssistant: "Personal AI assistant",
    featureSmartTasks: "Smart task management",
    featureFinanceTracking: "Finance tracking",
    featureWellnessMonitoring: "Wellness monitoring",
    trialInfo: "7-Day Free Trial",
    thenPrice: "Then RM9.90/month",
    cancelAnytime: "Cancel anytime. No credit card required to start.",
    
    // Dashboard
    dashboard: "Dashboard",
    profile: "Profile",
    logOut: "Log out",
    pendingTasks: "Pending Tasks",
    thisMonth: "This Month",
    activeGoals: "Active Goals",
    aiResponses: "AI Responses",
    askMindPilotAI: "Ask MindPilot AI",
    askAnything: "Ask me anything about your day, tasks, or goals...",
    thinking: "Thinking...",
    todaysTasks: "Today's Tasks",
    pending: "pending",
    noTasksYet: "No tasks yet. Add your first task!",
    
    // Tasks
    tasksTitle: "Tasks",
    tasksDescription: "Manage your tasks and let AI help you prioritize.",
    addNewTask: "Add a new task...",
    low: "Low",
    medium: "Medium",
    high: "High",
    add: "Add",
    loadingTasks: "Loading tasks...",
    
    // Finance
    financeTitle: "Finance",
    financeDescription: "Track your spending and income.",
    totalIncome: "Total Income",
    totalExpenses: "Total Expenses",
    addTransaction: "Add Transaction",
    expense: "Expense",
    income: "Income",
    amount: "Amount (RM)",
    description: "Description",
    general: "General",
    food: "Food",
    transport: "Transport",
    entertainment: "Entertainment",
    bills: "Bills",
    shopping: "Shopping",
    health: "Health",
    noTransactions: "No transactions yet. Add your first one!",
    
    // Wellness
    wellnessTitle: "Wellness",
    wellnessDescription: "Track your mood, energy, and sleep patterns.",
    todaysCheckIn: "Today's Check-in",
    mood: "Mood",
    energy: "Energy",
    sleepHours: "Sleep Hours",
    notes: "Notes (optional)",
    howAreYouFeeling: "How are you feeling today?",
    saveEntry: "Save Entry",
    recentEntries: "Recent Entries",
    noWellnessEntries: "No wellness entries yet. Start tracking today!",
    
    // Profile
    profileTitle: "Profile",
    profileDescription: "Manage your account and preferences.",
    subscription: "Subscription",
    premiumPlanActive: "Premium Plan Active",
    fullAccessDescription: "You have full access including unlimited AI, unlimited storage, and unlimited goals.",
    freeTrial: "Free Trial",
    daysRemaining: "days remaining",
    trialDescription: "Enjoy all Premium features for free for 7 days. After that, subscribe to continue.",
    subscribeNow: "Subscribe Now - RM9.90/month",
    trialExpired: "Trial Expired",
    trialExpiredDescription: "Your free trial has ended. Subscribe now to continue using MindPilot AI.",
    aiUsageToday: "AI Usage Today",
    geminiApiKey: "Google Gemini API Key",
    geminiApiKeyDescription: "Enter your Gemini API key to enable real AI.",
    getApiKeyFree: "Get free API key →",
    apiKeySaved: "API Key saved",
    remove: "Remove",
    save: "Save",
    
    // Trial Banner
    premiumActive: "Premium Active",
    unlimitedAI: "Unlimited AI & all features unlocked",
    subscribePrice: "Subscribe RM9.90/month",
    
    // Errors
    errorEmailInUse: "This email is already registered. Please use a different email.",
    errorWeakPassword: "Password is too weak. Please use a stronger password.",
    errorRegistration: "Registration error. Please try again.",
    errorInvalidCredentials: "Invalid email or password.",
    errorLogin: "Login error. Please try again.",
    errorGoogleLogin: "Google login error. Please try again.",
    errorUnauthorizedDomain: "This domain is not authorized for Firebase. Please use email/password.",
    errorPopupClosed: "Popup closed. Please try again.",
    
    // Validation
    firstNameRequired: "First name is required",
    lastNameRequired: "Last name is required",
    emailRequired: "Email is required",
    emailInvalid: "Invalid email format",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters",
    termsRequired: "You must agree to the terms",
    
    // Language
    language: "Language",
    selectLanguage: "Select Language",
  }
};

// Malay translations
const ms = {
  translation: {
    // Header
    features: "Ciri-ciri",
    howItWorks: "Cara ia berfungsi",
    pricing: "Harga",
    login: "Log masuk",
    startFreeTrial: "Mula Percubaan Percuma",
    
    // Hero
    tagline: "Pembantu AI kehidupan untuk dewasa 25–50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "Pembantu yang berfikir lebih awal untuk anda.",
    heroDescription: "Automatikkan tugas, wang, dan rutin harian anda dengan satu pembantu AI yang dibina untuk kehidupan sebenar — bukan hanya kerja.",
    aiPlansDay: "AI merancang hari anda",
    clearSpending: "Pandangan perbelanjaan jelas",
    smarterRoutines: "Rutin lebih pintar",
    oneAppForLife: "Satu aplikasi untuk kehidupan",
    tryFreeForever: "Cuba Percuma Selamanya",
    noCreditCard: "Tiada kad kredit diperlukan untuk pelan Percuma. Batal atau turun taraf bila-bila masa.",
    
    // Daily Plan
    todayWithMindPilot: "Hari ini dengan MindPilot",
    aiModeActive: "Mod AI: Aktif",
    dailyPlanGenerated: "Pelan harian dijana oleh AI",
    planningYourDay: "Ini cara saya merancang hari anda:",
    deepWorkBlock: "Blok kerja mendalam",
    highFocusTasks: "9:00–11:00 · Tugas fokus tinggi",
    billsMoneyCheckIn: "Semakan bil & wang",
    billDueIn3Days: "Anda ada 1 bil perlu dibayar dalam 3 hari",
    energyBreakStretch: "Rehat tenaga & regangan",
    basedOnCalendar: "3:00 PM · Berdasarkan kalendar anda",
    eveningRecap: "Ringkasan petang",
    summaryAt9PM: "Saya akan hantar ringkasan 60 saat pada 9 PM",
    priority: "Keutamaan",
    finance: "Kewangan",
    wellness: "Kesejahteraan",
    summary: "Ringkasan",
    
    // Features
    featuresTitle: "Semua yang anda perlukan, dikuasakan oleh AI.",
    featuresDescription: "MindPilot AI menggabungkan tugas, kewangan, rutin, bimbingan, dan ringkasan dalam satu pembantu pintar.",
    aiTaskPilot: "Pilot Tugas AI",
    aiTaskPilotDesc: "Tugas harian dijana automatik, pengisihan keutamaan, peringatan pintar",
    smartMoneyView: "Pandangan Wang Pintar",
    smartMoneyViewDesc: "Jejak perbelanjaan, lihat corak, dapat amaran bajet lembut",
    lifeOrganizerHub: "Hab Penganjur Kehidupan",
    lifeOrganizerHubDesc: "Simpan dokumen dan nota di satu tempat selamat dan boleh dicari",
    wellnessCoach: "Jurulatih Kesejahteraan",
    wellnessCoachDesc: "Tidur, rehat, dorongan pergerakan pada masa yang tepat",
    goalNavigator: "Navigasi Matlamat",
    goalNavigatorDesc: "Tetapkan matlamat bulanan dengan pelan tindakan mingguan realistik",
    smartSummaries: "Ringkasan Pintar",
    smartSummariesDesc: "AI membaca yang panjang, beri anda versi 10 saat",
    tasks: "Tugas",
    money: "Wang",
    organization: "Organisasi",
    habits: "Tabiat",
    goals: "Matlamat",
    summaries: "Ringkasan",
    tryNow: "Cuba Sekarang",
    
    // How it works
    howItWorksTitle: "Dari pendaftaran ke \"kehidupan autopilot\" dalam 3 langkah.",
    howItWorksDescription: "Mula dalam beberapa minit dan biarkan MindPilot mengambil alih beban mental.",
    step1Title: "Daftar & sambung",
    step1Desc: "Buat akaun anda dan beritahu MindPilot tentang matlamat dan tabiat anda.",
    step2Title: "AI belajar rutin anda",
    step2Desc: "MindPilot menganalisis corak anda dan mula membina sistem peribadi anda.",
    step3Title: "Kehidupan autopilot",
    step3Desc: "Bangun dengan hari yang dirancang, kewangan dijejak, dan peringatan kesejahteraan — semua automatik.",
    aiPoweredAutomation: "Automasi dikuasakan AI",
    learnsAndAdapts: "Belajar dan menyesuaikan dengan anda",
    
    // Pricing
    pricingTitle: "Harga mudah dan telus",
    pricingDescription: "Mula dengan percubaan percuma 7 hari atau buka semua dengan Premium.",
    freeForever: "Percubaan Percuma",
    premium: "Premium",
    lifetime: "7 hari percuma",
    perMonth: "/bulan",
    mostPopular: "Paling Popular",
    startFree: "Mula Percuma",
    start7DayTrial: "Mula Percubaan 7 Hari Percuma",
    
    // Free features
    freeFeature1: "15 respons AI sehari",
    freeFeature2: "Pengurusan tugas manual",
    freeFeature3: "Penjejakan mood asas",
    freeFeature4: "Sehingga 10 dokumen",
    freeFeature5: "3 matlamat sebulan",
    freeFeature6: "5 ringkasan sehari",
    
    // Premium features
    premiumFeature1: "Respons AI tanpa had",
    premiumFeature2: "Tugas harian dijana automatik",
    premiumFeature3: "Sinkronisasi kewangan pintar & wawasan",
    premiumFeature4: "Storan awan tanpa had",
    premiumFeature5: "Matlamat tanpa had + pelan tindakan",
    premiumFeature6: "Pemprosesan AI keutamaan",
    premiumFeature7: "Tiada iklan, sandaran disulitkan",
    
    // Footer
    privacy: "Privasi",
    terms: "Terma",
    support: "Sokongan",
    allRightsReserved: "Hak cipta terpelihara.",
    
    // Register/Login
    registerTitle: "Daftar Akaun Baru",
    loginTitle: "Log Masuk",
    welcomeBack: "Selamat kembali! Sila log masuk ke akaun anda",
    startTrialToday: "Mula percubaan percuma 7 hari anda hari ini",
    loginWithGoogle: "Log masuk dengan Google",
    registerWithGoogle: "Daftar dengan Google",
    or: "atau",
    firstName: "Nama Pertama",
    lastName: "Nama Akhir",
    email: "Email",
    password: "Kata Laluan",
    minChars: "Minimum 6 aksara",
    agreeToTerms: "Saya bersetuju dengan",
    termsAndConditions: "Terma & Syarat",
    and: "dan",
    privacyPolicy: "Dasar Privasi",
    startTrialButton: "Mula Percubaan Percuma",
    loginButton: "Log Masuk",
    alreadyHaveAccount: "Sudah ada akaun?",
    dontHaveAccount: "Belum ada akaun?",
    registerNow: "Daftar sekarang",
    backToHome: "← Kembali ke laman utama",
    
    // Register features
    whatYouGet: "Apa yang anda dapat",
    feature7DayTrial: "7 hari percubaan percuma",
    featureAIAssistant: "Pembantu AI peribadi",
    featureSmartTasks: "Pengurusan tugas pintar",
    featureFinanceTracking: "Penjejakan kewangan",
    featureWellnessMonitoring: "Pemantauan kesihatan",
    trialInfo: "Percubaan Percuma 7 Hari",
    thenPrice: "Kemudian RM9.90/bulan",
    cancelAnytime: "Batalkan bila-bila masa. Tiada kad kredit diperlukan untuk mula.",
    
    // Dashboard
    dashboard: "Papan Pemuka",
    profile: "Profil",
    logOut: "Log keluar",
    pendingTasks: "Tugas Tertunda",
    thisMonth: "Bulan Ini",
    activeGoals: "Matlamat Aktif",
    aiResponses: "Respons AI",
    askMindPilotAI: "Tanya MindPilot AI",
    askAnything: "Tanya saya apa sahaja tentang hari, tugas, atau matlamat anda...",
    thinking: "Berfikir...",
    todaysTasks: "Tugas Hari Ini",
    pending: "tertunda",
    noTasksYet: "Belum ada tugas. Tambah tugas pertama anda!",
    
    // Tasks
    tasksTitle: "Tugas",
    tasksDescription: "Urus tugas anda dan biarkan AI membantu mengutamakan.",
    addNewTask: "Tambah tugas baru...",
    low: "Rendah",
    medium: "Sederhana",
    high: "Tinggi",
    add: "Tambah",
    loadingTasks: "Memuatkan tugas...",
    
    // Finance
    financeTitle: "Kewangan",
    financeDescription: "Jejak perbelanjaan dan pendapatan anda.",
    totalIncome: "Jumlah Pendapatan",
    totalExpenses: "Jumlah Perbelanjaan",
    addTransaction: "Tambah Transaksi",
    expense: "Perbelanjaan",
    income: "Pendapatan",
    amount: "Jumlah (RM)",
    description: "Penerangan",
    general: "Umum",
    food: "Makanan",
    transport: "Pengangkutan",
    entertainment: "Hiburan",
    bills: "Bil",
    shopping: "Membeli-belah",
    health: "Kesihatan",
    noTransactions: "Belum ada transaksi. Tambah yang pertama!",
    
    // Wellness
    wellnessTitle: "Kesejahteraan",
    wellnessDescription: "Jejak mood, tenaga, dan corak tidur anda.",
    todaysCheckIn: "Daftar Masuk Hari Ini",
    mood: "Mood",
    energy: "Tenaga",
    sleepHours: "Jam Tidur",
    notes: "Nota (pilihan)",
    howAreYouFeeling: "Bagaimana perasaan anda hari ini?",
    saveEntry: "Simpan Entri",
    recentEntries: "Entri Terkini",
    noWellnessEntries: "Belum ada entri kesejahteraan. Mula jejak hari ini!",
    
    // Profile
    profileTitle: "Profil",
    profileDescription: "Urus akaun dan keutamaan anda.",
    subscription: "Langganan",
    premiumPlanActive: "Pelan Premium Aktif",
    fullAccessDescription: "Anda mempunyai akses penuh termasuk AI tanpa had, storan tanpa had, dan matlamat tanpa had.",
    freeTrial: "Percubaan Percuma",
    daysRemaining: "hari lagi",
    trialDescription: "Nikmati semua ciri Premium secara percuma untuk 7 hari. Selepas itu, langgan untuk terus menggunakan.",
    subscribeNow: "Langgan Sekarang - RM9.90/bulan",
    trialExpired: "Percubaan Tamat",
    trialExpiredDescription: "Tempoh percubaan percuma anda telah tamat. Langgan sekarang untuk terus menggunakan MindPilot AI.",
    aiUsageToday: "Penggunaan AI Hari Ini",
    geminiApiKey: "Kunci API Google Gemini",
    geminiApiKeyDescription: "Masukkan kunci API Gemini anda untuk mengaktifkan AI sebenar.",
    getApiKeyFree: "Dapatkan kunci API percuma →",
    apiKeySaved: "Kunci API telah disimpan",
    remove: "Buang",
    save: "Simpan",
    
    // Trial Banner
    premiumActive: "Premium Aktif",
    unlimitedAI: "AI tanpa had & semua ciri dibuka",
    subscribePrice: "Langgan RM9.90/bulan",
    
    // Errors
    errorEmailInUse: "Email ini sudah didaftarkan. Sila gunakan email lain.",
    errorWeakPassword: "Kata laluan terlalu lemah. Sila gunakan kata laluan yang lebih kuat.",
    errorRegistration: "Ralat pendaftaran. Sila cuba lagi.",
    errorInvalidCredentials: "Email atau kata laluan tidak sah.",
    errorLogin: "Ralat log masuk. Sila cuba lagi.",
    errorGoogleLogin: "Ralat log masuk Google. Sila cuba lagi.",
    errorUnauthorizedDomain: "Domain ini belum dibenarkan untuk Firebase. Sila gunakan email/kata laluan.",
    errorPopupClosed: "Popup ditutup. Sila cuba lagi.",
    
    // Validation
    firstNameRequired: "Nama pertama diperlukan",
    lastNameRequired: "Nama akhir diperlukan",
    emailRequired: "Email diperlukan",
    emailInvalid: "Format email tidak sah",
    passwordRequired: "Kata laluan diperlukan",
    passwordMinLength: "Kata laluan mesti sekurang-kurangnya 6 aksara",
    termsRequired: "Anda mesti bersetuju dengan terma",
    
    // Language
    language: "Bahasa",
    selectLanguage: "Pilih Bahasa",
  }
};

// Chinese translations
const zh = {
  translation: {
    features: "功能",
    howItWorks: "如何运作",
    pricing: "价格",
    login: "登录",
    startFreeTrial: "开始免费试用",
    tagline: "25-50岁成人的AI生活助手",
    heroTitle: "MindPilot AI",
    heroSubtitle: "为您提前思考的助手。",
    heroDescription: "用一个为真实生活而非仅仅工作而构建的AI助手自动化您的任务、金钱和日常事务。",
    dashboard: "仪表板",
    tasks: "任务",
    finance: "财务",
    wellness: "健康",
    profile: "个人资料",
    logOut: "登出",
    language: "语言",
    selectLanguage: "选择语言",
  }
};

// Spanish translations
const es = {
  translation: {
    features: "Características",
    howItWorks: "Cómo funciona",
    pricing: "Precios",
    login: "Iniciar sesión",
    startFreeTrial: "Comenzar prueba gratuita",
    tagline: "Asistente de vida AI para adultos de 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "El asistente que piensa por adelantado para ti.",
    heroDescription: "Automatiza tus tareas, dinero y rutinas diarias con un solo asistente de IA construido para la vida real, no solo para el trabajo.",
    dashboard: "Panel",
    tasks: "Tareas",
    finance: "Finanzas",
    wellness: "Bienestar",
    profile: "Perfil",
    logOut: "Cerrar sesión",
    language: "Idioma",
    selectLanguage: "Seleccionar idioma",
  }
};

// Arabic translations
const ar = {
  translation: {
    features: "الميزات",
    howItWorks: "كيف يعمل",
    pricing: "الأسعار",
    login: "تسجيل الدخول",
    startFreeTrial: "ابدأ التجربة المجانية",
    tagline: "مساعد حياة ذكي للبالغين 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "المساعد الذي يفكر مسبقاً من أجلك.",
    heroDescription: "أتمت مهامك وأموالك وروتينك اليومي مع مساعد ذكاء اصطناعي واحد مصمم للحياة الحقيقية - وليس فقط للعمل.",
    dashboard: "لوحة التحكم",
    tasks: "المهام",
    finance: "المالية",
    wellness: "العافية",
    profile: "الملف الشخصي",
    logOut: "تسجيل الخروج",
    language: "اللغة",
    selectLanguage: "اختر اللغة",
  }
};

// Japanese translations
const ja = {
  translation: {
    features: "機能",
    howItWorks: "使い方",
    pricing: "料金",
    login: "ログイン",
    startFreeTrial: "無料トライアルを開始",
    tagline: "25〜50歳の大人向けAIライフアシスタント",
    heroTitle: "MindPilot AI",
    heroSubtitle: "あなたのために先を考えるアシスタント。",
    heroDescription: "仕事だけでなく、実生活のために構築された単一のAIアシスタントで、タスク、お金、日常のルーティンを自動化します。",
    dashboard: "ダッシュボード",
    tasks: "タスク",
    finance: "財務",
    wellness: "ウェルネス",
    profile: "プロフィール",
    logOut: "ログアウト",
    language: "言語",
    selectLanguage: "言語を選択",
  }
};

// Korean translations
const ko = {
  translation: {
    features: "기능",
    howItWorks: "작동 방식",
    pricing: "가격",
    login: "로그인",
    startFreeTrial: "무료 체험 시작",
    tagline: "25-50세 성인을 위한 AI 생활 도우미",
    heroTitle: "MindPilot AI",
    heroSubtitle: "당신을 위해 미리 생각하는 도우미.",
    heroDescription: "일뿐만 아니라 실제 생활을 위해 구축된 단일 AI 도우미로 작업, 돈 및 일상을 자동화하세요.",
    dashboard: "대시보드",
    tasks: "작업",
    finance: "재무",
    wellness: "웰니스",
    profile: "프로필",
    logOut: "로그아웃",
    language: "언어",
    selectLanguage: "언어 선택",
  }
};

// French translations
const fr = {
  translation: {
    features: "Fonctionnalités",
    howItWorks: "Comment ça marche",
    pricing: "Tarifs",
    login: "Connexion",
    startFreeTrial: "Commencer l'essai gratuit",
    tagline: "Assistant de vie IA pour adultes de 25 à 50 ans",
    heroTitle: "MindPilot AI",
    heroSubtitle: "L'assistant qui pense à l'avance pour vous.",
    heroDescription: "Automatisez vos tâches, votre argent et vos routines quotidiennes avec un seul assistant IA conçu pour la vraie vie — pas seulement le travail.",
    dashboard: "Tableau de bord",
    tasks: "Tâches",
    finance: "Finances",
    wellness: "Bien-être",
    profile: "Profil",
    logOut: "Déconnexion",
    language: "Langue",
    selectLanguage: "Sélectionner la langue",
  }
};

// German translations
const de = {
  translation: {
    features: "Funktionen",
    howItWorks: "So funktioniert's",
    pricing: "Preise",
    login: "Anmelden",
    startFreeTrial: "Kostenlose Testversion starten",
    tagline: "KI-Lebensassistent für Erwachsene von 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "Der Assistent, der für Sie vorausdenkt.",
    heroDescription: "Automatisieren Sie Ihre Aufgaben, Finanzen und täglichen Routinen mit einem einzigen KI-Assistenten, der für das echte Leben gebaut wurde — nicht nur für die Arbeit.",
    dashboard: "Dashboard",
    tasks: "Aufgaben",
    finance: "Finanzen",
    wellness: "Wohlbefinden",
    profile: "Profil",
    logOut: "Abmelden",
    language: "Sprache",
    selectLanguage: "Sprache auswählen",
  }
};

// Indonesian translations
const id = {
  translation: {
    features: "Fitur",
    howItWorks: "Cara kerja",
    pricing: "Harga",
    login: "Masuk",
    startFreeTrial: "Mulai Uji Coba Gratis",
    tagline: "Asisten kehidupan AI untuk dewasa 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "Asisten yang berpikir lebih dulu untuk Anda.",
    heroDescription: "Otomatiskan tugas, uang, dan rutinitas harian Anda dengan satu asisten AI yang dibangun untuk kehidupan nyata — bukan hanya pekerjaan.",
    dashboard: "Dasbor",
    tasks: "Tugas",
    finance: "Keuangan",
    wellness: "Kesehatan",
    profile: "Profil",
    logOut: "Keluar",
    language: "Bahasa",
    selectLanguage: "Pilih Bahasa",
  }
};

// Hindi translations
const hi = {
  translation: {
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    pricing: "मूल्य निर्धारण",
    login: "लॉग इन करें",
    startFreeTrial: "मुफ्त परीक्षण शुरू करें",
    tagline: "25-50 वर्ष के वयस्कों के लिए AI जीवन सहायक",
    heroTitle: "MindPilot AI",
    heroSubtitle: "सहायक जो आपके लिए आगे सोचता है।",
    heroDescription: "एक AI सहायक के साथ अपने कार्यों, पैसे और दैनिक दिनचर्या को स्वचालित करें जो वास्तविक जीवन के लिए बनाया गया है — सिर्फ काम के लिए नहीं।",
    dashboard: "डैशबोर्ड",
    tasks: "कार्य",
    finance: "वित्त",
    wellness: "कल्याण",
    profile: "प्रोफ़ाइल",
    logOut: "लॉग आउट",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
  }
};

// Portuguese translations
const pt = {
  translation: {
    features: "Recursos",
    howItWorks: "Como funciona",
    pricing: "Preços",
    login: "Entrar",
    startFreeTrial: "Iniciar teste gratuito",
    tagline: "Assistente de vida AI para adultos de 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "O assistente que pensa à frente para você.",
    heroDescription: "Automatize suas tarefas, dinheiro e rotinas diárias com um único assistente de IA construído para a vida real — não apenas para o trabalho.",
    dashboard: "Painel",
    tasks: "Tarefas",
    finance: "Finanças",
    wellness: "Bem-estar",
    profile: "Perfil",
    logOut: "Sair",
    language: "Idioma",
    selectLanguage: "Selecionar idioma",
  }
};

// Thai translations
const th = {
  translation: {
    features: "คุณสมบัติ",
    howItWorks: "วิธีการทำงาน",
    pricing: "ราคา",
    login: "เข้าสู่ระบบ",
    startFreeTrial: "เริ่มทดลองใช้ฟรี",
    tagline: "ผู้ช่วยชีวิต AI สำหรับผู้ใหญ่อายุ 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "ผู้ช่วยที่คิดล่วงหน้าให้คุณ",
    heroDescription: "ทำให้งาน เงิน และกิจวัตรประจำวันของคุณเป็นอัตโนมัติด้วยผู้ช่วย AI ตัวเดียวที่สร้างขึ้นสำหรับชีวิตจริง — ไม่ใช่แค่งาน",
    dashboard: "แดชบอร์ด",
    tasks: "งาน",
    finance: "การเงิน",
    wellness: "สุขภาพ",
    profile: "โปรไฟล์",
    logOut: "ออกจากระบบ",
    language: "ภาษา",
    selectLanguage: "เลือกภาษา",
  }
};

// Vietnamese translations
const vi = {
  translation: {
    features: "Tính năng",
    howItWorks: "Cách hoạt động",
    pricing: "Giá cả",
    login: "Đăng nhập",
    startFreeTrial: "Bắt đầu dùng thử miễn phí",
    tagline: "Trợ lý cuộc sống AI cho người lớn 25-50",
    heroTitle: "MindPilot AI",
    heroSubtitle: "Trợ lý suy nghĩ trước cho bạn.",
    heroDescription: "Tự động hóa công việc, tiền bạc và thói quen hàng ngày của bạn với một trợ lý AI duy nhất được xây dựng cho cuộc sống thực — không chỉ công việc.",
    dashboard: "Bảng điều khiển",
    tasks: "Nhiệm vụ",
    finance: "Tài chính",
    wellness: "Sức khỏe",
    profile: "Hồ sơ",
    logOut: "Đăng xuất",
    language: "Ngôn ngữ",
    selectLanguage: "Chọn ngôn ngữ",
  }
};

// Available languages list
export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ms', name: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
];

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en,
      ms,
      zh,
      ja,
      ko,
      es,
      fr,
      de,
      pt,
      ar,
      hi,
      id,
      th,
      vi,
    },
    lng: 'en', // Set English as default
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ['localStorage', 'navigator'],
      caches: ['localStorage'],
      lookupLocalStorage: 'i18nextLng',
    },
  });

export default i18n;
